const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const code=fs.readFileSync(process.env.BOUTIQUE_TEST_APP||__dirname+'/app.js','utf8').replace("$('#refresh').onclick=load;\nload();",'');
const context=vm.createContext({console,Intl,Date,Math,Number,String,document:{querySelector(){return {}}}});
vm.runInContext(code,context);
const run=s=>vm.runInContext(s,context);
const near=(a,b)=>assert.ok(Math.abs(a-b)<.00001,`${a} != ${b}`);
run(`state={settings:{margin:50,pricing:'margin'},products:[{id:'p1',purchase:4500,currency:'INR',exchange:90,packaging:0,qty:2,reserved:0,shipment:'sh',weight:1,share:1},{id:'p2',purchase:9000,currency:'INR',exchange:90,packaging:0,qty:1,reserved:0,shipment:'sh',weight:4,share:3}],shipments:[{id:'sh',method:'quantity',domestic:9,international:18,duty:3,brokerage:0,other:0}],sales:[],returns:[]}`);
near(run("cost(product('p1'))"),60);near(run("msrp(product('p1'))"),120);
run("state.settings.pricing='markup'");near(run("msrp(product('p1'))"),90);
run("state.shipments[0].method='value'");near(run("allocation(product('p1'))"),7.5);near(run("allocation(product('p2'))"),15);
run("state.shipments[0].method='weight'");near(run("allocation(product('p1'))"),5);near(run("allocation(product('p2'))"),20);
run("state.shipments[0].method='manual'");near(run("allocation(product('p1'))"),3.75);near(run("allocation(product('p2'))"),22.5);
run("state.shipments[0].method='quantity'; state.sales=[{id:'s',product:'p1',qty:1,price:120,tax:10.5,expense:2,date:'2026-09-30'}]");
assert.equal(run("available(product('p1'))"),1);near(run("stats(state.sales,[]).profit"),58);near(run("stats(state.sales,[]).tax"),10.5);
run("state.returns=[{sale:'s',restock:true,date:'2026-10-01'}]");assert.equal(run("onhand(product('p1'))"),2);near(run("stats(state.sales,state.returns).profit"),-2);
run("state.returns[0].restock=false");near(run("stats(state.sales,state.returns).profit"),-62);assert.equal(run("onhand(product('p1'))"),1);
run("currentYear='2026';currentQuarter='3'");assert.equal(run("inQuarter('2026-09-30')"),true);assert.equal(run("inQuarter('2026-10-01')"),false);assert.equal(run("inQuarter('2025-09-30')"),false);
near(run('round(108.75/(1+8.75/100))'),100);
assert.ok(run("csv([['=HYPERLINK(1)','line\\nvalue',-12.5]])").includes("\"'=HYPERLINK(1)\""));
// Reconcile all imported landed costs against exact cached workbook allocation components.
const seed=JSON.parse(fs.readFileSync(__dirname+'/initial-workbook-import.json','utf8'));
context.seed=seed;run('state=seed');
assert.equal(run('state.products.reduce((n,p)=>n+onhand(p),0)'),43);
near(run("cost(product('import-row-9'))"),74.6517094017094);
near(run("cost(product('import-row-28'))"),204.84111111111113);
near(run('state.products.reduce((n,p)=>n+cost(p)*p.qty,0)'),3903.2688888888893);
console.log('Calculation tests passed: allocation, margin/markup, refunds, tax extraction, quarter boundaries, CSV safety, workbook reconciliation.');
run("state={settings:{margin:50},products:[{id:'p',purchase:50,currency:'USD',exchange:90,packaging:0,qty:2,reserved:0,shipment:''}],shipments:[],sales:[{id:'ship-sale',product:'p',qty:1,price:102,tax:0,expense:0,shippingCharge:10,shippingCost:7,shippingTaxable:0,taxable:false}],returns:[]}");
near(run('saleRevenue(state.sales[0])'),112);near(run('taxableBase(state.sales[0])'),0);
near(run('stats(state.sales,[]).productRevenue'),102);near(run('stats(state.sales,[]).shipping'),10);near(run('stats(state.sales,[]).profit'),55);
run('state.sales[0].shippingCost=null');assert.equal(run('stats(state.sales,[]).missingShipping'),1);near(run('stats(state.sales,[]).profit'),62);
run("state.sales[0].shippingCost=7;state.returns=[{sale:'ship-sale',restock:true}]");near(run('stats(state.sales,state.returns).revenue'),0);near(run('stats(state.sales,state.returns).profit'),-7);
run('state.sales[0].taxable=true;state.sales[0].shippingTaxable=4');near(run('taxableBase(state.sales[0])'),106);
near(run('round((119.1-10-4*.0875)/(1+.0875))'),100);
console.log('Shipping tests passed: income vs expense, missing costs, full-refund expenses, partial taxable shipping, included-tax extraction.');
